# Source: harbor/templates/jobservice/jobservice-secret-envvars.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: harbor-jobservice-envvars
  labels:
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-9.2.1
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: jobservice
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: secret-infra
  data:
    - name: REGISTRY_CREDENTIAL_PASSWORD
      key: secret/data/harbor/jobservice/envvars
      property: REGISTRY_CREDENTIAL_PASSWORD
  template:
    metadata:
      labels:
        app.kubernetes.io/name: harbor
        helm.sh/chart: harbor-9.2.1
        app.kubernetes.io/instance: harbor
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: jobservice
    type: Opaque
