apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: quay-operator
spec:
  targetNamespaces:
    - quay-enterprise
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator-tng
spec:
  channel: alpha
  installPlanApproval: Automatic
  name:  quay-tng
  source: quay-operator
  sourceNamespace: openshift-marketplace
  startingCSV: quay-operator.v0.0.1