apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: quay-operator
spec:
  targetNamespaces:
    - quay-enterprise
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-registry
spec:
  channel: stable
  name: project-quay
  source: operatorhubio-catalog
  sourceNamespace: operator-lifecycle-manager