apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
spec:
  targetNamespaces:
    - jx
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: project-quay
spec:
  channel: stable
  name: project-quay
  source: operatorhubio-catalog
  sourceNamespace: olm