apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem
spec:
  clair:
    enabled: true
  quay:
    deploymentStrategy: Recreate
    externalAccess:
      hostname: quay.app.example.com
    keepConfigDeployment: true
    skipSetup: false
