apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: quay-registry
spec:
  components:
    - kind: postgres
      managed: false
    - kind: redis
      managed: false
    - kind: clair
      managed: false
    - kind: objectstorage
      managed: false