apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: jx-quay-ecosystem
spec:
  quay:
    deploymentStrategy: Recreate
    livenessProbe:
      initialDelaySeconds: 120
      httpGet:
        path: /health/instance
        port: 8443
        scheme: HTTPS
    readinessProbe:
      initialDelaySeconds: 10
      httpGet:
        path: /health/instance
        port: 8443
        scheme: HTTPS
    externalAccess:
      type: LoadBalancer
      hostname: quay.dev.property.xyz
    registryBackends:
      - name: local
        local:
          storagePath: /opt/quayregistry