# Source: wiki/charts/postgresql/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: wikijs-postgresql
  labels:
    app: postgresql
    chart: postgresql-6.5.0
    release: "wikijs"
    heritage: "Helm"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: wiki
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    app: postgresql
    release: "wikijs"
    role: master
