# Source: jxboot-helmfile-resources/templates/environments.yaml
apiVersion: jenkins.io/v1
kind: Environment
metadata:
  labels:
    env: "staging"
    team: jx
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: "staging"
  namespace: jx
spec:
  source:
    ref: "master"
    url: https://github.com/property-xyz/stage_platform-cluster.git
  kind: Permanent
  label: Staging
  namespace: jx-staging
  promotionStrategy: "Auto"
  order: 100
  remoteCluster: true
