filepath: ""
helmfiles:
- path: helmfiles/cert-manager/helmfile.yaml
- path: helmfiles/jx/helmfile.yaml
- path: helmfiles/nginx/helmfile.yaml
- path: helmfiles/secret-infra/helmfile.yaml
- path: helmfiles/tekton-pipelines/helmfile.yaml
releases:
- chart: ./charts/olm
  name: olm
  namespace: operator-lifecycle-manager
- chart: ./charts/quay
  version: 1.0.0
  name: quay-operator
  namespace: quay-enterprise
templates: {}
renderedvalues: {}
