filepath: ""
helmfiles:
- path: helmfiles/cert-manager/helmfile.yaml
- path: helmfiles/jx/helmfile.yaml
- path: helmfiles/nginx/helmfile.yaml
- path: helmfiles/secret-infra/helmfile.yaml
- path: helmfiles/tekton-pipelines/helmfile.yaml
- path: helmfiles/upsource/helmfile.yaml
repositories:
- name: appscode
  url: https://charts.appscode.com/stable/
releases:
- chart: ./charts/olm
  name: olm
  namespace: operator-lifecycle-manager
- chart: ./charts/npmr
  name: npmrc
  namespace: jx
templates: {}
renderedvalues: {}
