apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: jx-dev
    devEnvApprovers:
    - dicolasi
    - kannan1
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "794657423961"
    provider: eks
    region: eu-west-2
    registry: 794657423961.dkr.ecr.eu-west-2.amazonaws.com
  environments:
  - key: dev
    owner: property-xyz
    repository: dev_platform-cluster
  - gitKind: github
    gitServer: https://github.com
    key: staging
    owner: property-xyz
    promotionStrategy: Auto
    remoteCluster: true
    repository: stage_platform-cluster
  - gitKind: github
    gitServer: https://github.com
    key: production
    owner: property-xyz
    promotionStrategy: Manual
    remoteCluster: true
    repository: prod_platform-cluster
  ingress:
    domain: dev.property.xyz
    externalDNS: true
    kind: ingress
    namespaceSubDomain: .
    tls:
      email: security@property.xyz
      enabled: true
      production: true
  pipelineUser:
    username: property-xyz-bot
  repository: nexus
  secretStorage: vault
  storage:
  - name: backup
    url: s3://backup-jx-dev-20201226153228023700000001
  - name: logs
    url: s3://logs-jx-dev-2020122409330095290000000b
  - name: reports
    url: s3://reports-jx-dev-20201226153228038300000002
  - name: repository
    url: s3://repository-jx-dev-20201226153228041000000004
  terraform: true
  vault:
    aws:
      dynamoDBRegion: eu-west-2
      dynamoDBTable: vault-unseal-jx-dev-7j6LENpQ
      iamUserName: jenkins-x-vault
      kmsKeyId: 5b04d0c6-f02c-4d3a-a5d3-9fd312acd717
      kmsRegion: eu-west-2
      s3Bucket: vault-unseal-jx-dev-20201226153228038800000003
      s3Region: eu-west-2
  webhook: lighthouse
