# Source: upsource/templates/backups-persistentvolumeclaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: backups
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: backups
  namespace: upsource
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
