# Source: upsource/templates/conf-persistentvolumeclaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: conf
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: conf
  namespace: upsource
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
