# Source: upsource/templates/logs-persistentvolumeclaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: logs
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: logs
  namespace: upsource
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
