# Source: upsource/templates/temp-persistentvolumeclaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: temp
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: temp
  namespace: upsource
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
