# Source: upsource/templates/upsource-claim0-persistentvolumeclaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: upsource-claim0
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: upsource-claim0
  namespace: upsource
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
