# Source: olm/templates/0000_50_olm_08-catalog-operator.deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-operator
  namespace: operator-lifecycle-manager
  labels:
    app: catalog-operator
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    wave.pusher.com/update-on-config-change: 'true'
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: catalog-operator
  template:
    metadata:
      labels:
        app: catalog-operator
    spec:
      serviceAccountName: olm-operator-serviceaccount
      containers:
        - name: catalog-operator
          command:
            - /bin/catalog
          args:
            - '-namespace'
            - operator-lifecycle-manager
            - -configmapServerImage=quay.io/operator-framework/configmap-operator-registry:latest
            - -util-image
            - quay.io/operator-framework/olm:master
          image: quay.io/operator-framework/olm:master
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8081
              name: metrics
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          terminationMessagePolicy: FallbackToLogsOnError
          env:
          resources:
            requests:
              cpu: 10m
              memory: 80Mi
      nodeSelector:
        kubernetes.io/os: linux
