# Source: olm/templates/0000_50_olm_13-operatorgroup-default.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: global-operators
  namespace: operator-lifecycle-manager
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
