# Source: olm/templates/0000_50_olm_01-olm-operator.serviceaccount.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: olm-operator-serviceaccount
  namespace: operator-lifecycle-manager
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
