# Source: acme/templates/cert-manager-prod-certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "tls-dev-property-xyz-p"
  labels:
    jenkins.io/letsencrypt-service: production
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  secretName: "tls-dev-property-xyz-p"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.dev.property.xyz"
  dnsNames:
    - "*.dev.property.xyz"
    - "dev.property.xyz"
