# Source: quay-operator/templates/quay-registry-crd.yaml
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: quay-registry
  namespace: quay-enterprise
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  components:
    - kind: postgres
      managed: false
    - kind: redis
      managed: false
    - kind: clair
      managed: false
    - kind: objectstorage
      managed: false
