# Source: quay-operator/templates/00_project-quay-operator.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: quay-operator
  namespace: quay-enterprise
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  targetNamespaces:
    - quay-enterprise
