# Source: harbor/templates/trivy/trivy-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: "harbor-harbor-trivy"
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  ports:
    - name: api-server
      protocol: TCP
      port: 8443
  selector:
    release: harbor
    app: "harbor"
    component: trivy
