# Source: harbor/templates/trivy/trivy-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: harbor-harbor-trivy
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: secret-infra
  data:
    - name: redisURL
      key: secret/data/harbor/harbor/trivy
      property: redisURL
    - name: gitHubToken
      key: secret/data/harbor/harbor/trivy
      property: gitHubToken
  template:
    metadata:
      labels:
        heritage: Helm
        release: harbor
        chart: harbor
        app: "harbor"
    type: Opaque
