apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  labels:
    name: quay-enterprise
    gitops.jenkins-x.io/pipeline: 'cluster'
    team: 'jx'
  name: quay-enterprise
spec: {}
status: {}
