# Source: harbor/templates/database/database-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "harbor-harbor-database"
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: secret-infra
  data:
    - name: POSTGRES_PASSWORD
      key: secret/data/harbor/harbor/database
      property: POSTGRES_PASSWORD
  template:
    metadata:
      labels:
        heritage: Helm
        release: harbor
        chart: harbor
        app: "harbor"
    type: Opaque
