# Source: harbor/charts/redis/templates/headless-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: harbor-redis-headless
  namespace: "jx"
  labels:
    app: redis
    chart: redis-12.2.2
    release: harbor
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    app: redis
    release: harbor
