# Source: harbor/templates/clair/clair-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: harbor-clair
  labels:
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-9.2.1
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: clair
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  ports:
    - name: clair
      port: 6060
    - name: health
      port: 6061
    - name: adapter
      port: 8080
  selector:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/component: clair
