filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: secret-infra
repositories:
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
releases:
- chart: jx3/kubernetes-external-secrets
  version: 6.2.2
  name: kubernetes-external-secrets
  values:
  - ../../versionStream/charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
  - jx-values.yaml
- chart: jx3/pusher-wave
  version: 0.4.12
  name: pusher-wave
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
