# Source: kubed/templates/apiregistration.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: kubed-apiserver-cert
  namespace: jx
  labels:
    helm.sh/chart: kubed-v0.12.0
    app.kubernetes.io/name: kubed
    app.kubernetes.io/instance: kubed
    app.kubernetes.io/version: "v0.12.0"
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: jx-vault
  data:
    - name: tls.crt
      key: secret/data/kubed/apiserver/cert
      property: tls.crt
    - name: tls.key
      key: secret/data/kubed/apiserver/cert
      property: tls.key
  template:
    metadata:
      labels:
        helm.sh/chart: kubed-v0.12.0
        app.kubernetes.io/name: kubed
        app.kubernetes.io/instance: kubed
        app.kubernetes.io/version: "v0.12.0"
        app.kubernetes.io/managed-by: Helm
    type: Opaque
