# Source: olm/templates/0000_50_olm_09-aggregated.clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aggregate-olm-edit
  labels:
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    gitops.jenkins-x.io/pipeline: 'cluster'
rules:
  - apiGroups: ["operators.coreos.com"]
    resources: ["subscriptions"]
    verbs: ["create", "update", "patch", "delete"]
  - apiGroups: ["operators.coreos.com"]
    resources: ["clusterserviceversions", "catalogsources", "installplans", "subscriptions"]
    verbs: ["delete"]
