# Source: harbor-resources/templates/aws-storageClass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  iopsPerGB: "10"
  fsType: ext4
