# Source: harbor/templates/portal/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "harbor-harbor-portal"
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    release: harbor
    app: "harbor"
    component: portal
