apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: property-xyz
    provider: https://github.com
    providerKind: github
    repositories:
    - name: prod_platform-cluster
    - name: stage_platform-cluster
    - name: tes-jx3-boot
    - name: test-jx3-spring
    scheduler: in-repo
  - owner: property-xyz-bot
    provider: https://github.com
    providerKind: github
    repositories:
    - name: test-jx3-angular
    scheduler: in-repo
