# Source: vault-instance/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-01-09T10:57:24Z"
  deletionTimestamp: null
  name: 'vault-instance-1.0.6'
  namespace: secret-infra
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: added variables
      sha: c6d812a0b59bc1f5a1091da694131b48726c6997
    - author:
        email: pat@patscott.io
        name: Patrick Lee Scott
      branch: master
      committer:
        email: pat@patscott.io
        name: Patrick Lee Scott
      message: |
        fix: set version for bankVaults, and upgrade Vault

        Signed-off-by: Patrick Lee Scott <pat@patscott.io>
      sha: 09d1fc177acecf377dbddd0c15d0739f3040975d
  gitHttpUrl: https://github.com/jenkins-x-charts/vault-instance
  gitOwner: jenkins-x-charts
  gitRepository: vault-instance
  name: 'vault-instance'
  releaseNotesURL: https://github.com/jenkins-x-charts/vault-instance/releases/tag/v1.0.6
  version: v1.0.6
status: {}
