# Source: vault-instance/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-01-03T15:41:42Z"
  deletionTimestamp: null
  name: 'vault-instance-1.0.5'
  namespace: secret-infra
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: added variables
      sha: 86bb7444b908e20668c902b5d10ba372c9ff2512
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: noreply@github.com
        name: GitHub
      message: 'chore: fix release'
      sha: 3197fc095da313d9c04c5eb461df6e62cda4f53e
  gitHttpUrl: https://github.com/jenkins-x-charts/vault-instance
  gitOwner: jenkins-x-charts
  gitRepository: vault-instance
  name: 'vault-instance'
  releaseNotesURL: https://github.com/jenkins-x-charts/vault-instance/releases/tag/v1.0.5
  version: v1.0.5
status: {}
