# Source: harbor/templates/registry/registry-dpl.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "harbor-harbor-registry"
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
    component: registry
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
  annotations:
    wave.pusher.com/update-on-config-change: 'true'
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      release: harbor
      app: "harbor"
      component: registry
  template:
    metadata:
      labels:
        heritage: Helm
        release: harbor
        chart: harbor
        app: "harbor"
        component: registry
      annotations:
        checksum/configmap: 37ba76dc3c13c86043ba8af1d91de4f1d1ba938114a433b2c7455f2471fd2ad3
        checksum/secret: d900feacd75e0180e84dcce5f67f3c077c64f99789763b2ad5ee9ec52a405808
        checksum/secret-jobservice: 9bdc4bdcd3c776f25305ba5741d1d25f5dbf608ce4a27afffab4574f467bccef
        checksum/secret-core: 1c817424e9c30f79d37a87595a1cd5ac91a3d1ae09ad19399acbf103c1c80703
        checksum/tls: 39a655e2a03ddde42044cdb488ae44594212fec82e70af2829810092ab552b3f
    spec:
      securityContext:
        fsGroup: 10000
      containers:
        - name: registry
          image: goharbor/registry-photon:v2.1.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              scheme: HTTPS
              port: 5443
            initialDelaySeconds: 300
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              scheme: HTTPS
              port: 5443
            initialDelaySeconds: 1
            periodSeconds: 10
          args: ["serve", "/etc/registry/config.yml"]
          envFrom:
            - secretRef:
                name: "harbor-harbor-registry"
          env:
            - name: INTERNAL_TLS_ENABLED
              value: "true"
            - name: INTERNAL_TLS_KEY_PATH
              value: /etc/harbor/ssl/registry/tls.key
            - name: INTERNAL_TLS_CERT_PATH
              value: /etc/harbor/ssl/registry/tls.crt
            - name: INTERNAL_TLS_TRUST_CA_PATH
              value: /etc/harbor/ssl/registry/ca.crt
          ports:
            - containerPort: 5443
            - containerPort: 5001
          volumeMounts:
            - name: registry-data
              mountPath: /storage
              subPath:
            - name: registry-root-certificate
              mountPath: /etc/registry/root.crt
              subPath: tls.crt
            - name: registry-htpasswd
              mountPath: /etc/registry/passwd
              subPath: passwd
            - name: registry-config
              mountPath: /etc/registry/config.yml
              subPath: config.yml
            - name: registry-internal-certs
              mountPath: /etc/harbor/ssl/registry
        - name: registryctl
          image: goharbor/harbor-registryctl:v2.1.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /api/health
              scheme: HTTPS
              port: 8443
            initialDelaySeconds: 300
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              scheme: HTTPS
              port: 8443
            initialDelaySeconds: 1
            periodSeconds: 10
          envFrom:
            - secretRef:
                name: "harbor-harbor-registry"
          env:
            - name: CORE_SECRET
              valueFrom:
                secretKeyRef:
                  name: harbor-harbor-core
                  key: secret
            - name: JOBSERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: harbor-harbor-jobservice
                  key: JOBSERVICE_SECRET
            - name: INTERNAL_TLS_ENABLED
              value: "true"
            - name: INTERNAL_TLS_KEY_PATH
              value: /etc/harbor/ssl/registry/tls.key
            - name: INTERNAL_TLS_CERT_PATH
              value: /etc/harbor/ssl/registry/tls.crt
            - name: INTERNAL_TLS_TRUST_CA_PATH
              value: /etc/harbor/ssl/registry/ca.crt
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: registry-data
              mountPath: /storage
              subPath:
            - name: registry-config
              mountPath: /etc/registry/config.yml
              subPath: config.yml
            - name: registry-config
              mountPath: /etc/registryctl/config.yml
              subPath: ctl-config.yml
            - name: registry-internal-certs
              mountPath: /etc/harbor/ssl/registry
      volumes:
        - name: registry-htpasswd
          secret:
            secretName: harbor-harbor-registry
            items:
              - key: REGISTRY_HTPASSWD
                path: passwd
        - name: registry-root-certificate
          secret:
            secretName: harbor-harbor-core
        - name: registry-config
          configMap:
            name: "harbor-harbor-registry"
        - name: registry-data
          persistentVolumeClaim:
            claimName: harbor-harbor-registry
        - name: registry-internal-certs
          secret:
            secretName: harbor-harbor-registry-internal-tls
