# Source: harbor/templates/registry/registry-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: "harbor-harbor-registry"
  labels:
    heritage: Helm
    release: harbor
    chart: harbor
    app: "harbor"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: secret-infra
  data:
    - name: REGISTRY_HTPASSWD
      key: secret/data/harbor/harbor/registry
      property: REGISTRY_HTPASSWD
    - name: REGISTRY_HTTP_SECRET
      key: secret/data/harbor/harbor/registry
      property: REGISTRY_HTTP_SECRET
    - name: REGISTRY_REDIS_PASSWORD
      key: secret/data/harbor/harbor/registry
      property: REGISTRY_REDIS_PASSWORD
  template:
    metadata:
      labels:
        heritage: Helm
        release: harbor
        chart: harbor
        app: "harbor"
    type: Opaque
