# Source: harbor/templates/registry/registry-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registry
  labels:
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-9.2.1
    app.kubernetes.io/instance: harbor
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: secret-infra
  data:
    - name: REGISTRY_HTPASSWD
      key: secret/data/harbor/registry
      property: REGISTRY_HTPASSWD
    - name: REGISTRY_HTTP_SECRET
      key: secret/data/harbor/registry
      property: REGISTRY_HTTP_SECRET
    - name: REGISTRY_REDIS_PASSWORD
      key: secret/data/harbor/registry
      property: REGISTRY_REDIS_PASSWORD
  template:
    metadata:
      labels:
        app.kubernetes.io/name: harbor
        helm.sh/chart: harbor-9.2.1
        app.kubernetes.io/instance: harbor
        app.kubernetes.io/managed-by: Helm
    type: Opaque
