# Source: lighthouse/templates/tekton-controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighthouse-tekton-controller
  labels:
    chart: "lighthouse-0.0.937"
    app: lighthouse-tekton-controller
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
  annotations:
    wave.pusher.com/update-on-config-change: 'true'
    jenkins-x.io/hash: '4f48354fa9c26537106c4eaf31e288fb79dce7eb9064187a0b5f00bfc4878b8f'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lighthouse-tekton-controller
  template:
    metadata:
      labels:
        app: lighthouse-tekton-controller
      annotations: {}
    spec:
      serviceAccountName: lighthouse-tekton-controller
      containers:
        - name: lighthouse-tekton-controller
          image: gcr.io/jenkinsxio/lighthouse-tekton-controller:0.0.937
          imagePullPolicy: IfNotPresent
          args:
            - --namespace=jx
            - --dashboard-url=http://dashboard.dev.property.xyz
            - --dashboard-template=namespaces/{{ .Namespace }}/pipelineruns/{{ .PipelineRun }}
          ports:
            - name: metrics
              containerPort: 8080
          env:
            - name: "LOGRUS_FORMAT"
              value: "json"
            - name: DEFAULT_PIPELINE_RUN_SERVICE_ACCOUNT
              value: "tekton-bot"
            - name: DEFAULT_PIPELINE_RUN_TIMEOUT
              value: "2h0m0s"
            - name: FILE_BROWSER
              value: "git"
            - name: JX_DEFAULT_IMAGE
              value: "gcr.io/jenkinsxio/builder-maven:2.1.142-761"
            - name: LIGHTHOUSE_DASHBOARD_TEMPLATE
              value: "namespaces/{{ .Namespace }}/pipelineruns/{{ .PipelineRun }}"
            - name: LIGHTHOUSE_VERSIONSTREAM_JENKINS_X_JX3_PIPELINE_CATALOG
              value: "a00fe9c8a5729337c3f046da2b3994fcd5740f52"
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 80m
              memory: 128Mi
      terminationGracePeriodSeconds: 180
      nodeSelector: {}
      affinity: {}
      tolerations: []
